[taxonomies]
  tag = 'tags'

[params]
  # To enable icons for browser (favicon) and mobile, generate them through
  # https://realfavicongenerator.net/, place under $HUGO_SITE_ROOT/static and
  # set `icons` to `true`.
  icons = false
  dateDisplayFormat = "Jan 2, 2006"
  # Insert your Mastodon username for link verification.
  # (https://docs.joinmastodon.org/user/profile/#verification)
  # mastodon = "username"
  twitterCards = true
  opengraph = true
  # If you want to render LaTeX with KaTeX, either set "math = true" to enable
  # globally or set "math = true" on individual pages in font matter to reduce
  # loading time for pages without LaTeX. The latter is encouraged.
  math = false
