[taxonomies]
  tag = 'tags'

[params]
  # Insert your Mastodon username for link verification.
  # (https://docs.joinmastodon.org/user/profile/#verification)
  # mastodon = "username"
  dateDisplayFormat = ":date_medium"
