[taxonomies]
  tag = 'tags'

[params]
  # favicon = "/icons/favicon.ico"
  dateDisplayFormat = "Jan 2, 2006"
  # Insert your Mastodon username for link verification.
  # (https://docs.joinmastodon.org/user/profile/#verification)
  # mastodon = "username"
  twitterCards = true
  opengraph = true
