name = 'Minimis'
license = 'MIT'
licenselink = 'https://github.com/kirillbobyrev/minimis/blob/master/LICENSE'
description = 'Minimalistic theme for personal blogging'

homepage = 'https://github.com/kirillbobyrev/minimis'
demosite = 'https://kirillbobyrev.github.io/minimis'

tags = ['blog', 'personal', 'minimal', 'clean', 'mobile']
features = ['katex', 'tags', 'toc']
min_version = '0.139.0'

[author]
  name = 'Kirill Bobyrev'
  homepage = 'https://kirillbobyrev.com/'
