baseURL = 'https://kirillbobyrev.github.io/minimis'
languageCode = 'en'
enableEmoji = true
theme = 'minimis'
title = 'minimis'
themesDir = '../..'

[params]
  description = 'minimalistic theme for Hugo'
  [params.author]
    name = 'Jon Doe'

[markup]
  [markup.highlight]
    guessSyntax = true
    style = 'github'
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
